import Image from "next/image";
import Link from "next/link";
import { conversao as c } from "@/content/conversao";
import { clientes } from "@/content/clientes";
import { Seta } from "@/components/ui/primitivos";
export function Provas(){return <div className="container-rf"><div className="proof-row">{c.provas.map((p)=><div key={p.titulo}><span aria-hidden="true" className="proof-check">✓</span><div><strong>{p.titulo}</strong><span>{p.texto}</span></div></div>)}</div></div>}
export function FaixaClientes(){const nomes=["MRV Engenharia","Direcional Engenharia","Brasal","Cyrela","Caixa Econômica Federal","GRU Airport"];return <section className="client-strip"><div className="container-rf"><div className="client-strip-heading"><p>{c.faixaClientes}</p><Link href="/clientes">{c.verClientes}<Seta/></Link></div><div className="client-logos">{nomes.map(n=>clientes.find(i=>i.nome===n)).filter(i=>!!i).map(i=><Image key={i.arquivo} src={`/imagens/clientes/${i.arquivo}`} alt={i.nome} width={150} height={60} sizes="130px"/>)}</div></div></section>}
export function EstruturaRf(){return <section className="rf-section rf-structure"><div className="container-rf structure-grid"><figure><Image src={c.estrutura.imagem} alt={c.estrutura.alt} width={1200} height={800} sizes="(min-width:1024px) 520px, 90vw"/><figcaption>{c.estrutura.legenda}</figcaption></figure><div><p className="rf-eyebrow">{c.estrutura.etiqueta}</p><h2>{c.estrutura.titulo}</h2><p className="rf-lead">{c.estrutura.texto}</p><div className="structure-benefits">{c.estrutura.itens.map(i=><div key={i.titulo}><span aria-hidden="true">✓</span><div><h3>{i.titulo}</h3><p>{i.texto}</p></div></div>)}</div><Link className="rf-text-link" href="/sobre">{c.estrutura.link}<Seta/></Link></div></div></section>}
export function CtaOrcamento(){return <section className="rf-final"><div className="container-rf"><div><p className="rf-eyebrow">{c.final.etiqueta}</p><h2>{c.final.titulo}</h2><p>{c.final.texto}</p></div><Link className="rf-button" href="/contato#orcamento">{c.orcamento}<Seta/></Link></div></section>}
