"use client";
import {useState,useRef,useEffect,type FormEvent} from "react";
import Link from "next/link";
import {site} from "@/content/site";
import {servicos} from "@/content/servicos";
import {conversao as c} from "@/content/conversao";
import {linkWhatsapp} from "@/lib/whatsapp";
import {IconeTelefone,IconeWhatsapp} from "@/components/ui/icones";
export function Orcamento({servicoInicial=""}:{servicoInicial?:string}){const f=c.formulario;const formulario=useRef<HTMLFormElement>(null);const [mensagem,setMensagem]=useState("");const [destino,setDestino]=useState("");const [canal,setCanal]=useState("");const [copiado,setCopiado]=useState("");
useEffect(()=>{
 const contexto=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!contexto?.registerTool)return;
 const ciclo=new AbortController();
 try{void Promise.resolve(contexto.registerTool({name:"preencher_orcamento_rf",description:"Preenche os campos visíveis do orçamento para revisão. Não envia mensagem nem abre outro aplicativo.",inputSchema:{type:"object",properties:{nome:{type:"string",minLength:1,maxLength:100},empresa:{type:"string",maxLength:150},cidade:{type:"string",minLength:1,maxLength:120},servico:{type:"string",enum:servicos.map(s=>s.nomeCurto)},detalhes:{type:"string",maxLength:1800}},required:["nome","cidade","servico"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(entrada:unknown)=>{
 if(!entrada||typeof entrada!=="object"||Array.isArray(entrada))throw Error("Dados inválidos");
 const dados=entrada as Record<string,unknown>;const limites:Record<string,number>={nome:100,empresa:150,cidade:120,servico:120,detalhes:1800};
 for(const [chave,valor] of Object.entries(dados)){if(!(chave in limites)||typeof valor!=="string"||valor.length>limites[chave])throw Error("Campo inválido");}
 if(!String(dados.nome??"").trim()||!String(dados.cidade??"").trim()||!servicos.some(s=>s.nomeCurto===dados.servico))throw Error("Informe nome, cidade e serviço válido");
 const form=formulario.current;if(!form)throw Error("Formulário indisponível");
 for(const chave of Object.keys(limites)){const campo=form.elements.namedItem(chave) as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement|null;if(campo)campo.value=String(dados[chave]??"");}
 setMensagem("");setDestino("");setCopiado("");form.scrollIntoView({block:"center"});return {status:"preenchido_para_revisao",servico:dados.servico,enviado:false};
 }},{signal:ciclo.signal})).catch(()=>{});}catch{/* Formulário convencional permanece disponível. */}
 return()=>ciclo.abort();
},[]);
function preparar(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const dados=new FormData(form);const escolhido=(e.nativeEvent as SubmitEvent).submitter?.getAttribute("value")??"email";const valores=[f.saudacao,`${f.nome}: ${dados.get("nome")}`,`${f.empresa}: ${dados.get("empresa")||"-"}`,`${f.cidade}: ${dados.get("cidade")}`,`${f.servico}: ${dados.get("servico")}`,`${f.detalhes}: ${dados.get("detalhes")||"-"}`];const mensagem=valores.join("\n");const url=escolhido==="whatsapp"?linkWhatsapp(mensagem):`mailto:${site.email}?subject=${encodeURIComponent(f.assunto)}&body=${encodeURIComponent(mensagem)}`;setMensagem(mensagem);setDestino(url);setCanal(escolhido);setCopiado("");const w=window as Window&{dataLayer?:Array<Record<string,unknown>>};w.dataLayer=w.dataLayer||[];w.dataLayer.push({event:"rf_quote_prepare",service:dados.get("servico"),channel:escolhido,page_path:window.location.pathname});if(escolhido==="whatsapp")window.open(url,"_blank","noopener,noreferrer");else window.location.href=url;}
async function copiar(){try{await navigator.clipboard.writeText(mensagem);setCopiado(f.copiado)}catch{setCopiado(f.erroCopia)}}
return <section className="rf-section quote-section" id="orcamento"><div className="container-rf quote-grid"><div><p className="rf-eyebrow">{f.etiqueta}</p><h2>{f.titulo}</h2><p className="rf-lead">{f.texto}</p><div className="quote-contact"><span>{f.telefone}</span><a href={site.telefone.href}><IconeTelefone/>{site.telefone.exibicao}</a><a href={`mailto:${site.email}`}>{site.email}</a></div></div><form ref={formulario} className="quote-form" onSubmit={preparar}><p className="form-note">{f.obrigatorio}</p><div className="form-grid"><label>{f.nome} *<input name="nome" autoComplete="name" required maxLength={100}/></label><label>{f.empresa}<input name="empresa" autoComplete="organization" maxLength={150}/></label><label>{f.cidade} *<input name="cidade" autoComplete="address-level2" required maxLength={120}/></label><label>{f.servico} *<select name="servico" required defaultValue={servicoInicial}><option value="" disabled>{f.escolha}</option>{servicos.map(s=><option key={s.slug} value={s.nomeCurto}>{s.nomeCurto}</option>)}<option>{f.outro}</option></select></label></div><label>{f.detalhes}<textarea name="detalhes" rows={3} placeholder={f.placeholder} maxLength={1800}/></label><div className="form-buttons"><button type="submit" value="whatsapp" className="quote-whatsapp"><IconeWhatsapp/>{f.whatsapp}</button><button type="submit" value="email" className="quote-email">{f.email}</button></div><p className="form-note">{f.aviso} <Link href="/politica-de-privacidade">{f.privacidade}</Link></p>{mensagem&&<div className="quote-result" role="status"><p>{f.sucesso}</p><textarea aria-label={f.revisao} readOnly value={mensagem} rows={6}/><div className="result-actions"><a href={destino} target={canal==="whatsapp"?"_blank":undefined} rel="noreferrer">{canal==="whatsapp"?f.abrirWhats:f.abrirEmail}</a><button type="button" onClick={copiar}>{f.copiar}</button></div>{copiado&&<p>{copiado}</p>}</div>}</form></div></section>}
